#datasource
spring:
  datasource:
    dynamic:
      primary: diceMaster
      datasource:
        diceMaster:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://dice-mysql:3306/dice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: root
logging:
  level:
    root: info
    com.bihell.dice.mapper: trace
  pattern:
    console: '%p%m%n'